---
name: "Pull Request Reviewed"

on:
  pull_request_review:
    types: [submitted]

jobs:
  add-waiting-response:
    if: github.event.review.state != 'approved' && github.actor != github.event.pull_request.user.login
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          mkdir -p wr_actions
          echo ${{ github.owner }} > wr_actions/ghowner.txt
          echo ${{ github.repository }} > wr_actions/ghrepo.txt
          echo ${{ github.event.pull_request.number }} > wr_actions/prnumber.txt
          echo "add-waiting-response" > wr_actions/action.txt
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: wr_actions
  remove-waiting-response:
    if: github.actor == github.event.pull_request.user.login
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          mkdir -p wr_actions
          echo ${{ github.owner }} > wr_actions/ghowner.txt
          echo ${{ github.repository }} > wr_actions/ghrepo.txt
          echo ${{ github.event.pull_request.number }} > wr_actions/prnumber.txt
          echo "remove-waiting-response" > wr_actions/action.txt
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: wr_actions
